lib/shibr_web/router.ex
defmodule ShibrWeb.Router do
  use ShibrWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ShibrWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/breed/:breed", PageController, :index

    resources "/history", DogHistoryController, except: [:new, :create, :edit, :update]
    
    get "/visual", PageController, :visual
  end

  # Other scopes may use custom stacks.
  # scope "/api", ShibrWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ShibrWeb.Telemetry
    end
  end
end

lib/shibr_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1>Welcome to Shibr the newest place to view random Shiba images.</h1>
  <p>Making the world a better place one random Shiba picture at a time.</p>
</section>

<section >
  <%= img_tag(@main_dog) %>
</section>
<%= link("New Dog!", to: Routes.page_path(@conn, :index, @breed), class: "button") %>
<%= link("Dog History!!!", to: Routes.dog_history_path(@conn, :index), class: "button") %>
<%= link("Visual Breed Picker", to: Routes.page_path(@conn, :visual), class: "button") %>
<ul>
  <%= for breed <- @breeds do %>
    <li><%= link(breed, to: Routes.page_path(@conn, :index, breed)) %> </li>
  <% end %>
</ul>

lib/shibr_web/templates/page/visual.html.eex
<ul>
  <%= for breed_image <- @breeds do %>
    <li> <%= img_tag(breed_image.url) %> <%= link(breed_image.breed, to: Routes.page_path(@conn, :index, breed_image.breed)) %> </li>
  <% end %>
</ul>